# Generated by Django 6.1 on 2026-09-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_deliveryperson_order_delivery_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, help_text='Additional product photo 2', null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, help_text='Additional product photo 3', null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_proof',
            field=models.ImageField(blank=True, help_text='Upload purchase bill, invoice, or receipt as proof of ownership', null=True, upload_to='products/purchase_proof/'),
        ),
        migrations.AddField(
            model_name='product',
            name='serial_number',
            field=models.CharField(blank=True, default='', help_text='Serial or model number of the product', max_length=150),
        ),
    ]
