# Generated by Django 6.1 on 2026-09-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_product_image2_product_image3_product_purchase_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='visible_to_user',
            field=models.BooleanField(default=True, help_text="Whether the order is still visible in the customer's My Orders list"),
        ),
    ]
